---
name: test-vpc
cidr: 192.168.0.0/16
subnets: 
  - az: us-west-2a
    cidr: 192.168.0.0/18
    public: false
  - az: us-west-2b
    cidr: 192.168.64.0/18
    public: false
  - az: us-west-2c
    cidr: 192.168.128.0/18
    public: false
  - az: us-west-2a
    cidr: 192.168.192.0/20
    public: true
  - az: us-west-2b
    cidr: 192.168.208.0/20
    public: true
  - az: us-west-2c
    cidr: 192.168.224.0/20
    public: true

